<a href="https://colab.research.google.com/github/dhirajdmv/dhirajdmv/blob/main/Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
a = "hello"
print(a)


hello


In [9]:
import numpy as np
print(np.__version__)

1.21.6


In [13]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr[0])

1


In [4]:
import numpy as np
arr = np.array ([1,2,3,4,5],dtype=np.float64)
arr

array([1., 2., 3., 4., 5.])

In [7]:
import numpy as np
ar= np.array([[1,2,3],[4,5,6],[7,8,9]])
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
import numpy as np
arr=np.zeros(5,dtype=float)
arr

array([0., 0., 0., 0., 0.])

In [25]:
import numpy as np
arr = np.random.rand(2,3)
arr

array([[0.10246281, 0.77764507, 0.32515516],
       [0.07685995, 0.96599401, 0.33798427]])

In [29]:
import numpy as np
arr=np.full((2,2),10)
arr


array([[10, 10],
       [10, 10]])

In [30]:
import numpy as np
arr=np.eye(3,k=2)
arr

array([[0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
import numpy as np
arr=np.arange(2,8,2)
arr

array([2, 4, 6])

In [36]:
import numpy as np
arr=np.linspace(2,4,10)
arr

array([2.        , 2.22222222, 2.44444444, 2.66666667, 2.88888889,
       3.11111111, 3.33333333, 3.55555556, 3.77777778, 4.        ])

In [8]:
import numpy as np

a = np.zeros(2)
b = a.flatten()
c = a.ravel()
print('original shape :', a.shape)


original shape : (2,)


In [9]:
import pandas 
myDataset = {
    'cars': ["BMW", "BENTLEY", "Ford"] ,
    'passings':[3,7,1]
}
myVar= pandas.DataFrame(myDataset)
print(myVar)

      cars  passings
0      BMW         3
1  BENTLEY         7
2     Ford         1
